DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS TRANSFERENCIAS;

CREATE TABLE USUARIOS (
	UID SERIAL PRIMARY KEY, 
	NOMBRE VARCHAR(50),
	BALANCE FLOAT CHECK (BALANCE >= 0));
	
CREATE TABLE TRANSFERENCIAS (
	UID SERIAL PRIMARY KEY, 
	EMISOR INT, 
	RECEPTOR INT, 
	MONTO FLOAT, 
	FECHA TIMESTAMP, 
	FOREIGN KEY (EMISOR) REFERENCES USUARIOS(UID), 
	FOREIGN KEY (RECEPTOR) REFERENCES USUARIOS(UID));
	